### ISSUE TITLE
Deploying site fails with npm

### ISSUE THREAD

**Issue by willettk** [zooniverse/data.galaxyzoo.org#19]
I tried deploying the new changes from my terminal (after giving myself access to the Amazon buckets). There seems to be a problem with the local npm version, but I'm not sure on how to fix it. 

Terminal: 
```
[willettk@zrak data.galaxyzoo.org]$ npm run-script deploy

> data.galaxyzoo.org@0.0.1 deploy /Users/willettk/Astronomy/Research/GalaxyZoo/data.galaxyzoo.org
> cake compile && publisssh ./public zooniverse-static/data.galaxyzoo.org

  compiled public/styles/application.css
Local: ./public
Bucket: zooniverse-static
Prefix: data.galaxyzoo.org
/Users/willettk/Astronomy/Research/GalaxyZoo/data.galaxyzoo.org/node_modules/publisssh/node_modules/aws-sdk/lib/sequential_executor.js:261
        throw err;
              ^
TypeError: Cannot read property 'length' of null
  at Object.AWS.util.buffer.concat (/Users/willettk/Astronomy/Research/GalaxyZoo/data.galaxyzoo.org/node_modules/publisssh/node_modules/aws-sdk/lib/util.js:116:29)
  at Request.HTTP_DONE (/Users/willettk/Astronomy/Research/GalaxyZoo/data.galaxyzoo.org/node_modules/publisssh/node_modules/aws-sdk/lib/event_listeners.js:214:36)
  at Request.callListeners (/Users/willettk/Astronomy/Research/GalaxyZoo/data.galaxyzoo.org/node_modules/publisssh/node_modules/aws-sdk/lib/sequential_executor.js:132:20)
  at Request.emit (/Users/willettk/Astronomy/Research/GalaxyZoo/data.galaxyzoo.org/node_modules/publisssh/node_modules/aws-sdk/lib/sequential_executor.js:100:10)
  at Request.emitEvent (/Users/willettk/Astronomy/Research/GalaxyZoo/data.galaxyzoo.org/node_modules/publisssh/node_modules/aws-sdk/lib/request.js:408:10)
  at IncomingMessage.onEnd (/Users/willettk/Astronomy/Research/GalaxyZoo/data.galaxyzoo.org/node_modules/publisssh/node_modules/aws-sdk/lib/event_listeners.js:184:26)
  at IncomingMessage.emit (events.js:129:20)
  at _stream_readable.js:908:16
  at process._tickCallback (node.js:355:11)


npm ERR! Darwin 13.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "run-script" "deploy"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE
npm ERR! data.galaxyzoo.org@0.0.1 deploy: `cake compile && publisssh ./public zooniverse-static/data.galaxyzoo.org`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the data.galaxyzoo.org@0.0.1 deploy script 'cake compile && publisssh ./public zooniverse-static/data.galaxyzoo.org'.
npm ERR! This is most likely a problem with the data.galaxyzoo.org package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cake compile && publisssh ./public zooniverse-static/data.galaxyzoo.org
npm ERR! You can get their info via:
npm ERR!     npm owner ls data.galaxyzoo.org
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/willettk/Astronomy/Research/GalaxyZoo/data.galaxyzoo.org/npm-debug.log
```

And the contents of my ```npm-debug.log```:
```
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'run-script', 'deploy' ]
2 info using npm@2.5.1
3 info using node@v0.12.0
4 verbose run-script [ 'predeploy', 'deploy', 'postdeploy' ]
5 info predeploy data.galaxyzoo.org@0.0.1
6 info deploy data.galaxyzoo.org@0.0.1
7 verbose unsafe-perm in lifecycle true
8 info data.galaxyzoo.org@0.0.1 Failed to exec deploy script
9 verbose stack Error: data.galaxyzoo.org@0.0.1 deploy: `cake compile && publisssh ./public zooniverse-static/data.galaxyzoo.org`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:213:16)
9 verbose stack     at EventEmitter.emit (events.js:110:17)
9 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:14:12)
9 verbose stack     at ChildProcess.emit (events.js:110:17)
9 verbose stack     at maybeClose (child_process.js:1008:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1080:5)
10 verbose pkgid data.galaxyzoo.org@0.0.1
11 verbose cwd /Users/willettk/Astronomy/Research/GalaxyZoo/data.galaxyzoo.org
12 error Darwin 13.4.0
13 error argv "node" "/usr/local/bin/npm" "run-script" "deploy"
14 error node v0.12.0
15 error npm  v2.5.1
16 error code ELIFECYCLE
17 error data.galaxyzoo.org@0.0.1 deploy: `cake compile && publisssh ./public zooniverse-static/data.galaxyzoo.org`
17 error Exit status 1
18 error Failed at the data.galaxyzoo.org@0.0.1 deploy script 'cake compile && publisssh ./public zooniverse-static/data.galaxyzoo.org'.
18 error This is most likely a problem with the data.galaxyzoo.org package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     cake compile && publisssh ./public zooniverse-static/data.galaxyzoo.org
18 error You can get their info via:
18 error     npm owner ls data.galaxyzoo.org
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]
```

**Comment by willettk** [comment]
If @chrissnyder or someone else can deploy this for me, that's also fine for now, but I'd like to figure out how to make changes myself in the future.

**Comment by willettk** [comment]
Aha. Fixed it by using the older version of node (```0.10.38```).
