### ISSUE TITLE
Deploying new code

### ISSUE THREAD

**Issue by willettk** [zooniverse/data.galaxyzoo.org#20]
I thought I'd successfully deployed the new http://data.galaxyzoo.org site (commands ran successfully), but I don't see any of the changes in the live web version. Is there something I'm missing, @chrissnyder?

```
[willettk@zrak data.galaxyzoo.org]$ npm run-script deploy

> data.galaxyzoo.org@0.0.1 deploy /Users/willettk/Astronomy/Research/GalaxyZoo/data.galaxyzoo.org
> cake compile && publisssh ./public zooniverse-static/data.galaxyzoo.org

  compiled public/styles/application.css
Local: ./public
Bucket: zooniverse-static
Prefix: data.galaxyzoo.org
```

**Comment by chrissnyder** [comment]
Publisssh (the script used to deploy the site) expects your env variable to have `AMAZON_ACCESS_KEY_ID` and `AMAZON_SECRET_ACCESS_KEY` available with credentials that give you permission to the specified bucket/path. Since I don't see it uploading anything after the plan, it's likely failing there.

https://github.com/brian-c/publisssh

**Comment by willettk** [comment]
I did set both of those variables (though I didn't include it in the issue
for mild security reasons). Echoing them in the terminal shows that they're
set, but I get the same results when I try to deploy.

**Comment by chrissnyder** [comment]
Can you test connecting to that bucket/path with some other program and see if you can connect?

**Comment by willettk** [comment]
Tried with Cyberduck; login failed.

```
Listing directory failed. Please contact your web hosting service provider
for assistance.
```

I used these successfully a few months ago, but don't know if any login
details have changed since then ...

**Comment by willettk** [comment]
Same results, both for deploying the site and connecting through Cyberduck.

**Comment by willettk** [comment]
Hi @chrissnyder,

I want to figure out why this isn't working, but getting it actually live
is more important right now. Could you or one of the other devs deploy it
for me?

Thanks a ton.

**Comment by chrissnyder** [comment]
Deployed.

**Comment by willettk** [comment]
Looks good. Thanks, Chris!

**Comment by willettk** [comment]
I can access the data.galaxyzoo.org bucket now through Cyberduck. Will post a new issue if I have issues deploying changes.

**Comment by willettk** [comment]
Just made some changes to the master branch (4b4120e64fec0f7b08f96d1524d590238d13ea46) and tried to deploy again. Same failure modes as before. 

I've verified that the AWS keys I use do work for the zooniverse-static bucket - through Cyberduck, eg, I can upload and download files without issues.

@brian-c - is this a problem with publisssh, perhaps? Or with the version of node that's required?

```
[willettk@zrak data.galaxyzoo.org]$ npm run-script deploy

> data.galaxyzoo.org@0.0.1 deploy /Users/willettk/Astronomy/Research/GalaxyZoo/data.galaxyzoo.org
> cake compile && publisssh ./public zooniverse-static/data.galaxyzoo.org

  compiled public/styles/application.css
Local: ./public
Bucket: zooniverse-static
Prefix: data.galaxyzoo.org
/Users/willettk/Astronomy/Research/GalaxyZoo/data.galaxyzoo.org/node_modules/publisssh/node_modules/aws-sdk/lib/sequential_executor.js:261
        throw err;
              ^
TypeError: Cannot read property 'length' of null
  at Object.AWS.util.buffer.concat (/Users/willettk/Astronomy/Research/GalaxyZoo/data.galaxyzoo.org/node_modules/publisssh/node_modules/aws-sdk/lib/util.js:116:29)
  at Request.HTTP_DONE (/Users/willettk/Astronomy/Research/GalaxyZoo/data.galaxyzoo.org/node_modules/publisssh/node_modules/aws-sdk/lib/event_listeners.js:214:36)
  at Request.callListeners (/Users/willettk/Astronomy/Research/GalaxyZoo/data.galaxyzoo.org/node_modules/publisssh/node_modules/aws-sdk/lib/sequential_executor.js:132:20)
  at Request.emit (/Users/willettk/Astronomy/Research/GalaxyZoo/data.galaxyzoo.org/node_modules/publisssh/node_modules/aws-sdk/lib/sequential_executor.js:100:10)
  at Request.emitEvent (/Users/willettk/Astronomy/Research/GalaxyZoo/data.galaxyzoo.org/node_modules/publisssh/node_modules/aws-sdk/lib/request.js:408:10)
  at IncomingMessage.onEnd (/Users/willettk/Astronomy/Research/GalaxyZoo/data.galaxyzoo.org/node_modules/publisssh/node_modules/aws-sdk/lib/event_listeners.js:184:26)
  at IncomingMessage.emit (events.js:129:20)
  at _stream_readable.js:908:16
  at process._tickCallback (node.js:355:11)


npm ERR! Darwin 13.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "run-script" "deploy"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE
npm ERR! data.galaxyzoo.org@0.0.1 deploy: `cake compile && publisssh ./public zooniverse-static/data.galaxyzoo.org`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the data.galaxyzoo.org@0.0.1 deploy script 'cake compile && publisssh ./public zooniverse-static/data.galaxyzoo.org'.
npm ERR! This is most likely a problem with the data.galaxyzoo.org package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cake compile && publisssh ./public zooniverse-static/data.galaxyzoo.org
npm ERR! You can get their info via:
npm ERR!     npm owner ls data.galaxyzoo.org
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/willettk/Astronomy/Research/GalaxyZoo/data.galaxyzoo.org/npm-debug.log
```

**Comment by chrissnyder** [comment]
Use node `0.10.x`

**Comment by willettk** [comment]
WORKED. Will put a note in the README.
